ARG VERSION=22.04
FROM ubuntu:${VERSION}

ARG HOSTUSER

# To prevent dialog box while install dependencies using apt-get
ENV DEBIAN_FRONTEND=noninteractive

RUN echo "Ubuntu Linux ${VERSION}" >> /etc/release

# Install software packages
RUN apt-get update && apt-get install -y \
 pkg-config curl wget unzip file libxml2-dev libxmlsec1-openssl openssl libssl-dev \
 git libglib2.0-dev libsocket++1 python3-dev python3 python3-pip pigz libncurses5 \
 fastboot bison flex swig cpanminus shellcheck \
 liblocal-lib-perl libxml-simple-perl uuid-dev \
 zlib1g-dev binutils-aarch64-linux-gnu rsync dotnet-sdk-8.0

# AOSP build requirements
RUN apt-get install -y \
 aspnetcore-runtime-8.0 libperl4-corelibs-perl pv zlib1g dotnet-runtime-8.0 \
 git-core gnupg flex bison build-essential zip curl zlib1g-dev libc6-dev-i386 \
 x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc \
 unzip fontconfig dosfstools e2fsprogs fdisk kpartx mtools rsync sudo

# uboot build requirements
RUN apt-get install -y \
  gcc gcc-aarch64-linux-gnu bc bison build-essential coccinelle \
  device-tree-compiler dfu-util efitools flex gdisk graphviz imagemagick \
  libgnutls28-dev libguestfs-tools libncurses-dev \
  libpython3-dev libsdl2-dev libssl-dev lz4 lzma lzma-alone openssl \
  pkg-config python3 python3-asteval python3-coverage python3-filelock \
  python3-pkg-resources python3-pycryptodome python3-pyelftools \
  python3-pytest python3-pytest-xdist python3-sphinxcontrib.apidoc \
  python3-sphinx-rtd-theme python3-subunit python3-testtools \
  python3-venv swig uuid-dev

# Debug tools
RUN apt-get update && apt-get install -y tree bash-completion strace vim

# Add repo tool
RUN curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/local/bin/repo && chmod +x /usr/local/bin/repo

# Add default user with empty password
RUN useradd --password U6aMy0wojraho --shell /bin/bash -u 4186280 $HOSTUSER && \
    usermod -aG sudo $HOSTUSER && \
    usermod -aG users $HOSTUSER && \
    echo "$HOSTUSER ALL = (ALL) ALL" >> /etc/sudoers

# Clean-Up
RUN apt-get autoremove -y && apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
